### ISSUE TITLE
Consider adding a --version flag

### ISSUE THREAD

**Issue by DannyBen** [c0redumb/yahoo_quote_download#13]
Thanks for the nice utility.

It would be nice to have the customary `--version` flag, to just show version number.

In addition, I opened a small PR for minor README fixes.

**Comment by c0redumb** [comment]
If you do "yqdownload -h", thje version number is a part of the help message. I can probably add a "--version" option if it helps.

I will merge the PR and there are probably a few other places where "begining" and "starting" are used interchangeably. I will fix those.

Thanks for the comments.

**Comment by c0redumb** [comment]
Added in version v0.3.2. Thanks for the suggestions.
