### ISSUE TITLE
unauthorized

### ISSUE THREAD

**Issue by Fulvioo** [c0redumb/yahoo_quote_download#15]
I'm using this tool since a couple of years and it's excellent; anyway it's a couple of days that I am experiencing this problem (unauthorized error). I tried it from different places and with different ip addresses but still not solving the problem.
Might it be due to changes on Yahoo's policies? thanks

**Comment by jenzj** [comment]
Also ran into this yesterday and today (3/9/20 - 3/10/20).  Using yqdownload (as recommended), here are my tests spread over two days:

**3/9/20**
9:20 AM PST
yqdownload -t MSFT -f test.txt -e 2020-02-28 -b 2020-01-01 -v 5
Downloading MSFT ...
('     Ticker:', 'MSFT')
('  Beginning:', '2020-01-01')
('     Ending:', '2020-02-28')
('       File:', 'test.txt')
Try 1/5 failed
Try 2/5 failed
Try 3/5 failed
Try 4/5 failed
Try 5/5 failed
!!! MSFT: Download unsuccessful!

12:15 PM PST
yqdownload -t MSFT -f test.txt -e 2020-02-28 -b 2020-01-01 -v 5
Downloading MSFT ...
('     Ticker:', 'MSFT')
('  Beginning:', '2020-01-01')
('     Ending:', '2020-02-28')
('       File:', 'test.txt')
Try 1/5 failed
Try 2/5 failed
Try 3/5 failed
Try 4/5 failed
Try 5/5 failed
!!! MSFT: Download unsuccessful!

**3/10/20**
12:43 PM PST
yqdownload -t MSFT -f test.txt -e 2020-02-28 -b 2020-01-01 -v 5
Downloading MSFT ...
('     Ticker:', 'MSFT')
('  Beginning:', '2020-01-01')
('     Ending:', '2020-02-28')
('       File:', 'test.txt')
Try 1/5 failed
Try 2/5 failed
Try 3/5 failed
Try 4/5 failed
Try 5/5 failed
!!! MSFT: Download unsuccessful!

I believe the authorization with Yahoo has changed.  BTW documentation on the beginning date needs updating to -b.  Thanks,

JJ

**Comment by c0redumb** [comment]
It looks like all download has stopped working since March 6, 2020.

I will take a look when I have some time. It may take a while as I have my day job that I need to take care of.

**Comment by c0redumb** [comment]
It has been fixed. For some reason, Yahoo does not respond to the original user agent string I used. Apparent this has starting to occur in the last couple of days. It has been fixed now in v0.3.1.

Please update to the latest version by

`pip install --update yahoo-quote-download`
