### ISSUE TITLE
Unexpected `Invalid date in data` error

### ISSUE THREAD

**Issue by DannyBen** [c0redumb/yahoo_quote_download#17]
Running this:

```
yqdownload -t ^GSPC -f gspc.csv
```

generates this error

```
!!! ^GSPC: Invalid date 2021-07-23 in data
```

but the date seems perfectly valid

**Comment by c0redumb** [comment]
The code pulls out new data after the last day of the existing data file. Sometimes Yahoo return date in the wrong range (usually overlap the last day but not always). So those duplicated date are thrown out with an error message you saw.
