### ISSUE TITLE
The same feature set as before?

### ISSUE THREAD

**Issue by andersborgabiro** [c0redumb/yahoo_quote_download#5]
Not issues per se, except possibly in terms of complementing the documentation:

Is there also company/ticker status information? By not adding start, end and interval, like before? 

Does the crumb expire, or can it be saved for use over time?

I will of course experiment with this.

**Comment by c0redumb** [comment]
Any findings on these questions? Please feel free to complete the documentation with any additional information.

**Comment by andersborgabiro** [comment]
My impression is that this is completely shut down. I haven't seen anything to the contrary.

https://www.programmableweb.com/news/oh-about-api-yahoo-killed-without-warning-developers/analysis/2017/11/10

**Comment by andersborgabiro** [comment]
I use it successfully and get company information another (unofficial) way.

**Comment by c0redumb** [comment]
It's good that it works. I will close this issue for now. Thank you.
