### ISSUE TITLE
'begindate' outside of time.mktime range

### ISSUE THREAD

**Issue by JackJacko** [c0redumb/yahoo_quote_download#9]
Hello,

The current implementation of the load_yahoo_quote function cannot use dates prior to 1970/01/01 due to the limited range of time.mktime. Would it be possible/relevant to modify the load_yahoo_quote function so that it accepts earlier dates? 

On paper I think calendar.timegm would do the trick - it outputs prior dates as negative numbers, which is also the format accepted for parameter 'period1' in the Yahoo URL for dates before 1970/01/01. However I've tried to modify the function accordingly (note the date format change):

`tb = calendar.timegm(time.strptime(begindate+":4","%Y-%m-%d:%H"))`
`te = calendar.timegm(time.strptime(enddate+":18","%Y-%m-%d:%H"))`

and get an 'invalid literal for int() with base 10' ValueError in exchange, which seems weird not only because both lines output correctly when run in isolation outside of the function, but because the error is marked at line 84, which is the '# Prepare the parameters and the URL' comment!

**Comment by tecfu** [comment]
At the time of writing, Yahoo! Finance historical stock data is only available back to 6/1/1972. 

Therefore it would be pointless to make this change. Issue should be closed.

**Comment by c0redumb** [comment]
Thanks for the comments. I will close this issue.
